apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: your-namespace-name
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
    defaultRequest:
      memory: 512Mi
    max:
      memory: 1Gi
    min:
      memory: 128Mi