apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: your-namespace-name
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
    defaultRequest:
      cpu: 500m
    max:
      cpu: "1"
    min:
      cpu: 100m