apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    tier: frontend
    app: httpd
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]
      capabilities:
        add: ["MAC_ADMIN"]
