apiVersion: v1
kind: Pod
metadata:
  name: toleration-example
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "example-key"
      operator: "Equal"
      value: "example-value"
      effect: "NoSchedule"